
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/3.30.5/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/3.30.5/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ichp09"
      binary: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ichp09"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ichp09'
        
        Run Build Command(s): C:/Users/Льоша/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_42cee/fast
        C:/Users/╦№ю°р/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_42cee.dir\\build.make CMakeFiles/cmTC_42cee.dir/build
        mingw32-make[1]: Entering directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ichp09'
        mingw32-make[1]: *** No rule to make target 'C:/Users/╨Ы╤М╨╛╤И╨░/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeCCompilerABI.c', needed by 'CMakeFiles/cmTC_42cee.dir/CMakeCCompilerABI.c.obj'.  Stop.
        mingw32-make[1]: Leaving directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-ichp09'
        mingw32-make: *** [Makefile:126: cmTC_42cee/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe"
    directories:
      source: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n4v8q3"
      binary: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n4v8q3"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n4v8q3'
        
        Run Build Command(s): C:/Users/Льоша/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_4f002/fast
        C:/Users/╦№ю°р/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_4f002.dir\\build.make CMakeFiles/cmTC_4f002.dir/build
        mingw32-make[1]: Entering directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n4v8q3'
        process_begin: CreateProcess(NULL, C:\\Users\\╨Ы╤М╨╛╤И╨░\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E cmake_echo_color --switch= "--progress-dir=D:\\ItStep\\C++\\JANUARY\\Overload operators (29.01.25)\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-n4v8q3\\CMakeFiles" --progress-num=1 "Building C object CMakeFiles/cmTC_4f002.dir/testCCompiler.c.obj", ...) failed.
        make (e=2): The system cannot find the file specified.\x0d
        mingw32-make[1]: *** [CMakeFiles\\cmTC_4f002.dir\\build.make:76: CMakeFiles/cmTC_4f002.dir/testCCompiler.c.obj] Error 2
        mingw32-make[1]: Leaving directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-n4v8q3'
        mingw32-make: *** [Makefile:126: cmTC_4f002/fast] Error 2
        
      exitCode: 2
...

---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "a.exe"
      
      The C compiler identification is GNU, found in:
        D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/3.30.5/CompilerIdC/a.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/g++.exe 
      Build flags: 
      Id flags:  
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "a.exe"
      
      The CXX compiler identification is GNU, found in:
        D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/3.30.5/CompilerIdCXX/a.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeDetermineCompilerABI.cmake:74 (try_compile)"
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-oo1vmo"
      binary: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-oo1vmo"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-oo1vmo'
        
        Run Build Command(s): C:/Users/Льоша/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_9add8/fast
        C:/Users/╦№ю°р/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_9add8.dir\\build.make CMakeFiles/cmTC_9add8.dir/build
        mingw32-make[1]: Entering directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-oo1vmo'
        mingw32-make[1]: *** No rule to make target 'C:/Users/╨Ы╤М╨╛╤И╨░/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeCCompilerABI.c', needed by 'CMakeFiles/cmTC_9add8.dir/CMakeCCompilerABI.c.obj'.  Stop.
        mingw32-make[1]: Leaving directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-oo1vmo'
        mingw32-make: *** [Makefile:126: cmTC_9add8/fast] Error 2
        
      exitCode: 2
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/cmake/win/x64/share/cmake-3.30/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Check for working C compiler: C:/Users/\u041b\u044c\u043e\u0448\u0430/AppData/Local/Programs/CLion/bin/mingw/bin/gcc.exe"
    directories:
      source: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vck4yq"
      binary: "D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vck4yq"
    cmakeVariables:
      CMAKE_C_FLAGS: ""
      CMAKE_C_FLAGS_DEBUG: "-g"
      CMAKE_EXE_LINKER_FLAGS: ""
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vck4yq'
        
        Run Build Command(s): C:/Users/Льоша/AppData/Local/Programs/CLion/bin/cmake/win/x64/bin/cmake.exe -E env VERBOSE=1 C:/Users/Льоша/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe -f Makefile cmTC_2cd8a/fast
        C:/Users/╦№ю°р/AppData/Local/Programs/CLion/bin/mingw/bin/mingw32-make.exe  -f CMakeFiles\\cmTC_2cd8a.dir\\build.make CMakeFiles/cmTC_2cd8a.dir/build
        mingw32-make[1]: Entering directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vck4yq'
        process_begin: CreateProcess(NULL, C:\\Users\\╨Ы╤М╨╛╤И╨░\\AppData\\Local\\Programs\\CLion\\bin\\cmake\\win\\x64\\bin\\cmake.exe -E cmake_echo_color --switch= "--progress-dir=D:\\ItStep\\C++\\JANUARY\\Overload operators (29.01.25)\\cmake-build-debug\\CMakeFiles\\CMakeScratch\\TryCompile-vck4yq\\CMakeFiles" --progress-num=1 "Building C object CMakeFiles/cmTC_2cd8a.dir/testCCompiler.c.obj", ...) failed.
        make (e=2): The system cannot find the file specified.\x0d
        mingw32-make[1]: *** [CMakeFiles\\cmTC_2cd8a.dir\\build.make:76: CMakeFiles/cmTC_2cd8a.dir/testCCompiler.c.obj] Error 2
        mingw32-make[1]: Leaving directory 'D:/ItStep/C++/JANUARY/Overload operators (29.01.25)/cmake-build-debug/CMakeFiles/CMakeScratch/TryCompile-vck4yq'
        mingw32-make: *** [Makefile:126: cmTC_2cd8a/fast] Error 2
        
      exitCode: 2
...
